name = "SIRIUS"
uuid = "3581e6f0-5a2a-4fbf-9499-336905df69aa"
authors = ["Augustin Bussy"]
version = "0.1.1"

[deps]
OpenBLAS32 = "51095b67-9e93-468d-a683-508b52f74e81"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
SIRIUS_jll = "6b659922-2939-5935-a7a2-1bdd48c7820f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.9"
OpenBLAS32 = "0.1"
JSON3 = "1.14"
MPI = "0.20"
SIRIUS_jll = "7.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
