# Greatly inspired by DFTK CI
name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  schedule:
    - cron:  '0 4 * * 6'  # Run every Saturday
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  build_matrix:
    name: Build Test Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - run: |
          cat > matrix.yaml <<- EOM
          - {mode: stable,  arch: x64,     os: ubuntu-latest,     payload:             }
          - {mode: stable,  arch: aarch64, os: ubuntu-24.04-arm,  payload:             }
          - {mode: stable,  arch: x64,     os: ubuntu-latest,     payload: mpi         }
          - {mode: stable,  arch: aarch64, os: ubuntu-24.04-arm,  payload: mpi         }
          EOM
      - name: Convert to JSON
        run: |
          python3 -c 'import sys, yaml, json; json.dump(yaml.safe_load(sys.stdin), sys.stdout)' < matrix.yaml > matrix.json
      - id: set-matrix
        run: echo "matrix={\"include\":$(cat matrix.json)}" >> $GITHUB_OUTPUT
  test:
    name: Julia ${{ matrix.mode }} - ${{ matrix.os }} - ${{ matrix.payload }}
    needs: build_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    env:
      GKS_ENCODING: utf8

    steps:
      - uses: actions/checkout@v5

      - name: Setup Julia stable
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'
          arch: ${{ matrix.arch }}
        if: ${{ matrix.mode == 'stable' }}

      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          SIRIUS_TEST_ARGS: ${{ matrix.payload }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
